# Generated by Django 3.1.1 on 2021-01-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210111_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listings',
            new_name='listing',
        ),
    ]
